blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, is_published

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/view', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('<int:pk>/delete', BlogDeleteView.as_view(), name='blog_delete'),
    path('<int:pk>/', is_published, name='is_published'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(
        max_length=150,
        verbose_name="Заголовок",
        help_text="Введите заголовок")

    slug = models.CharField(
        max_length=100,
        verbose_name="slug")

    content = models.TextField(
        verbose_name='содержимое',
        blank=True,
        null=True,
    )

    image = models.ImageField(
        upload_to="blog/image",
        verbose_name="Изображение",
        help_text="Загрузите изображение",
        blank=True,
        null=True,

    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания")


    is_published = models.BooleanField(
        default=True,
        verbose_name='Опубликовано'
    )

    count_views = models.IntegerField(
        default=0,
        verbose_name='Просмотры'
    )

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from blog.models import Blog
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify


class BlogCreateView(CreateView):
    model = Blog
    template_name = 'blog/blog_form.html'
    fields = ('title', 'content', 'image')
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'image')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    context_object_name = 'blogs'
    paginate_by: int = 10

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    fields = ('title', 'content', 'image')
    success_url = reverse_lazy('blog:blog_list')


def is_published(request, pk):
    is_published_blog = get_object_or_404(Blog, pk=pk)
    if is_published_blog:
        is_published_blog = False
    else:
        is_published_blog = True

    is_published_blog.save()

    return redirect(reverse('blog:blog_list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'home.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        <p class="card-text">Действительно хотите удалить {{ object.name }} ?</p>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-outline-danger">
                            Удалить
                        </button>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-sm btn-outline-secondary">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }} </h4>
                </div>
                <div class="card-body">
                    <p class="card-text"> Ссылка: {{ object.slug }}</p>
                    <p class="card-text">Содержимое: {{ object.content }}</p>
                    <p class="card-text">Дата создания: {{ object.created_at }}</p>
                    <p class="card-text">Кол-во просмотров: {{ object.views_count }}</p>
                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блоги наших покупателей</h1>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="d-grid gap-2 col-2 mx-auto mb-4">
        <a href="{% url 'blog:blog_create' %}" type="button" class="btn btn-lg btn-block btn-primary">Создать блог</a>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            {% if object.is_published %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h4 class="card-text text-center">{{ object.title }}</h4>
                        <img class="card-img-top mb-4" src="{{ object.image | media_filter }}">
                        <p class="card-text">{{ object.body | truncatechars:100 }}</p>
                        <div class="d-grid gap-2  mx-auto">
                            <a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-sm btn-primary">Посмотреть</a>
                            <a href="{% url 'blog:blog_update' object.pk %}" class="btn btn-sm btn-secondary">Изменить</a>
                        </div>
                        <a href="{% url 'blog:blog_delete' object.pk %}" type="button"
                           class="btn btn-md mt-3 btn-danger" style="float:right">Удалить</a>
                        <p class="text-body-secondary text-sm"></p>
                        <figcaption class="blockquote-footer mt-4">
                            Создано: {{ object.created_at }}
                        </figcaption>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}