blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, is_published

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/view', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('<int:pk>/delete', BlogDeleteView.as_view(), name='blog_delete'),
    path('<int:pk>/', is_published, name='is_published'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView,
    ProductDetailView,
    contacts,
    ProductDeleteView,
    ProductCreateView,
    ProductUpdateView
)

app_name = CatalogConfig.name
urlpatterns = [
    path("", ProductListView.as_view(), name="products_list"),
    path("catalog/<int:pk>/", ProductDetailView.as_view(), name="product_detail"),
    path("delete/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),

    path('contacts/', contacts, name='contacts'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path('blog/', include('blog.urls', namespace='blog')),
]

catalog/models.py
from django.db import models


# Create your models here.

class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование категории",
        help_text="Укажите название категории",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Опишите категории",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование продукта",
        help_text="Укажите название продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Опишите продукт",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to="catalog/image",
        blank=True,
        null=True,
        verbose_name="Фото",
        help_text="Загрузите фото продукта",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='category'
    )
    price_pay = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Цена за покупку",
        help_text="Введите цену"
    )
    created_at = models.DateTimeField(
        verbose_name="Дата создания записи",
        help_text="Введите дату",
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name="Дата изменения записи",
        help_text="Введите дату",
        auto_now=True
    )
    manufactured_at = models.DateTimeField(
        verbose_name="Дата производства продукта",
        help_text="Введите дату",
    )
    is_published = models.BooleanField(
        default=True,
        verbose_name='Опубликовано',
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "price_pay"]

    def __str__(self):
        return f'{self.name}, {self.category}'


class Version(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='product',
        verbose_name="Продукт",
    )
    num_version = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Номер версии",
        help_text="Введите номер версии"
    )
    name_version = models.CharField(
        max_length=100,
        verbose_name="Наименование версии",
        help_text="Укажите название версии",
    )
    status_version = models.BooleanField(default=True, verbose_name="Статус версии",)

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["product", "num_version"]

    def __str__(self):
        return f'{self.product}'

catalog/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from catalog.form import ProductForm, VersionForm
from catalog.models import Product, Version


class ProductListView(ListView):
    model = Product
    template_name = "catalog/products_list.html"
    context_object_name = "products"
    ordering = ["price_pay"]  # сортирует товары по цене в порядке возрастания
    paginate_by = 10  # на странице показывает товары по 10 штук

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, *args, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        for product in context_data['object_list']:
            status_version = Version.objects.filter(product=product, status_version=True).first()
            product.status_version = status_version
        return context_data


class ProductDetailView(DetailView):
    model = Product
    # template_name = "catalog/product_detail.html"  # выводит подробную информацию о товаре


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"Имя пользователя : {name}\nТелефон: {phone}\nСообщение: {message}")

    return render(request, 'catalog/contacts.html')


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products_list')


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm

    success_url = reverse_lazy('catalog:products_list')


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

catalog/templates/catalog/contacts.html
{% extends 'catalog/home.html' %}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Магазин щедрости</h1>
        <p class="lead text-muted">Пишите</p>
        <p>
            <a href="#" class="btn btn-primary my-2"><i class="bi bi-android"></i>О нас</a>
        </p>
    </div>
</section>
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-1 font-weight-normal">Отправить заявку</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

catalog/templates/catalog/home.html
{% load static %}
<!doctype html>
<html lang="ru" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Магазин щедрости</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include "catalog/includes/inc_menu.html" %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Магазин щедрости</h1>
    <p class="lead">Магазин щедрости - это отличный вариант закупки продуктов и товаров на всю семью, предоставляем Вам
        к выбору:
    </p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="https://sky.pro/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script
        src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous">
</script>
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        <p class="card-text">Действительно хотите удалить {{ object.name }} ?</p>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-outline-danger">
                            Удалить
                        </button>
                        <a href="{% url 'catalog:products_list' %}" class="btn btn-sm btn-outline-secondary">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <img src="{{ product.image | media_filter }}">
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ product.name }}</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>Описание: {{ product.description }}</li>
                    <li>Категория: {{ product.category }}</li>
                    <li>Цена: {{ product.price_pay }}</li>
                    <li>Дата изменения: {{ product.manufactured_at }}</li>
                </ul>
                <div class="btn-group">
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
                <div class="btn-group">
                    <a href="{% url 'catalog:product_delete' object.pk %}" type="button"
                           class="btn btn-lg btn-danger" style="float:right">Удалить
                    </a>
                   </div>
                <div class="btn-group">
                    <a href="{% url 'catalog:product_update' object.pk %}" type="button"
                           class="btn btn-lg m-3  btn-outline-primary" style="float:right">Редактировать
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                  {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

catalog/templates/catalog/products_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="d-grid gap-2 col-2 mx-auto mb-4">
    <a href="{% url 'catalog:product_create' %}" type="button" class="btn btn-lg btn-block btn-primary">Создать
        продукт</a>
</div>
<div class="row text-center">
    {% for product in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <img src="{{ product.image | media_filter }}">

            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ product.name }}</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>Описание: {{ product.description | truncatechars_html:100 }}</li>
                </ul>
                <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}"
                   role="button">Подробнее</a>
                <div class="card m-4 box-shadow">
                    {% for version in product.versions.all %}
                        {% if version.status_version %}
                            <p>Версия: {{ version.num_version }} Название: {{ version.name_version }}</p>
                        {% endif %}
                    {% endfor %}
                </div>

            </div>

        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}